name: country_search
description: Fast and lightweight country selector for Flutter with localization, fuzzy search, and ISO 3166 support â€” only 113KB.
version: 2.6.4
homepage: https://github.com/stanislavworldin/country_search
repository: https://github.com/stanislavworldin/country_search
issue_tracker: https://github.com/stanislavworldin/country_search/issues
documentation: https://github.com/stanislavworldin/country_search#readme
topics:
  - flags
  - country
  - picker
  - search
  - codes

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # No assets needed for this package screenshots:

screenshots:
  - description: "Country Picker with search functionality"
    path: screenshots/1.png
